spring.application.name=projeto-ambiental
server.port=8080

# Define o tamanho máximo de arquivo e requisição para o upload de fotos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Inicialização automática do banco de dados usando o arquivo data.sql
spring.sql.init.mode=always


# ===================================================================
# OPÇÃO 1: CONFIGURAÇÃO PARA POSTGRESQL (Recomendado se usar mapas/PostGIS)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_atividade_extensionista?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===================================================================
# OPÇÃO 2: CONFIGURAÇÃO PARA MYSQL (Caso prefira este banco)
# ===================================================================
# Para usar o MySQL, remova o "#" das 5 linhas abaixo e coloque "#" nas 5 linhas do PostgreSQL acima
# spring.datasource.url=jdbc:mysql://localhost:3306/bd_atividade_extensionista?createDatabaseIfNotExist=true&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE / JPA (Comum para ambos os bancos)
# ===================================================================
# update: Atualiza a estrutura de tabelas automaticamente sem apagar os dados existentes
spring.jpa.hibernate.ddl-auto=validate

# Mostra e formata as consultas SQL geradas pelo Java no console do PC (excelente para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.security.token.secret=12345678

